mysite/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'

urlpatterns = [
    path('<id>/post_edit/',views.post_edit,name="post_edit"),
    path('<id>/post_delete/',views.post_delete,name="post_delete"),
    path('<id>/favourite_post/',views.favourite_post,name="favourite_post"),
    path('', views.post_list,name='post_list'),
    path('/<id>/<slug>/',views.post_detail,name='post_detail'),
    path('post_create/',views.post_create, name="post_create"),
    path('user_login/',views.user_login,name='user_login'),
    path('user_logout/',views.user_logout,name='user_logout'),
    path('register/',views.register, name='register'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    path('like/',views.like_post,name='like_post'),
    path('favourite/', views.post_favourite_list, name="post_favourite_list")

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'),name='blog'),


    #password reset url's

    path('',include('django.contrib.auth.urls')),
    path('oauth/',include('social_django.urls',namespace="social")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'blog/style.css' %}">

    
</head>
<body>
  {% include 'navbar.html' %}      
<div class="container-fluid">
        {% block content %}
        {% endblock %}
        {% include 'blog/footer.html' %}
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(event){

      $('#delete').click(function(){
        return confirm("Are you sure to delete this post");
      });

      $('.reply-btn').click(function() {
        $(this).parent().parent().next('.replied-comments').fadeToggle()
      });

      $(function(){
        setTimeout(function(){
          $('.alert').slideUp(1000);
        }, 2000);
      })
      $(document).on('click', '#like', function(event){
        event.preventDefault();
        var pk= $(this).attr('value');
        $.ajax({
          type: 'POST',
          url:'{% url "blog:like_post" %}',
          data:{'id':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
          dataType : 'json',
          success: function(response){
            $('#like-section').html(response['form'])
            console.log($('#like-section').html(response['form']));
          },
          error: function(rs, e){
            console.log(rs.responseText);
          },
        });
      });
    });


    $(document).on('submit', '.comment-form', function(event){
      event.preventDefault();
      console.log($(this).serialize());
      $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data:$(this).serialize(),
        dataType:'json',
        success: function(response){
          $('.main-comment-section').html(response['form']);
          $('textarea').val('');
          $('.reply-btn').click(function() {
          $(this).parent().parent().next('.replied-comments').fadeToggle()
          $('textarea').val('');

        });

        },
        error: function(rs, e){
          console.log(rs.responseText);
        },
      });
    });



    $(document).on('submit', '.reply-form', function(event){
      event.preventDefault();
      console.log($(this).serialize());
      $.ajax({
        type: 'POST',
        url: $(this).attr('action'),
        data:$(this).serialize(),
        dataType:'json',
        success: function(response){
          $('.main-comment-section').html(response['form']);
          $('textarea').val('');
          $('.reply-btn').click(function() {
          $(this).parent().parent().next('.replied-comments').fadeToggle()
          $('textarea').val('');

        });

        },
        error: function(rs, e){
          console.log(rs.responseText);
        },
      });
    });



    </script>

</body>
</html>

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">AK Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!-- <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
  -->
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% if request.user.profile.photo %}
                 <img src="{{ request.user.profile.photo.url }}" alt="" class="navbar-img">
                 {% else %}
                 <img src="/media/alo.png" alt="" class="navbar-img">
                  {% endif %}
                  <span>Hi {{ request.user|capfirst }}</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'blog:edit_profile' %}">My profile</a>
                    <a class="dropdown-item" href="{% url 'blog:post_create' %}">Post Create</a>
                    <a class="dropdown-item" href="{% url 'blog:post_favourite_list' %}">Favourite</a>                
                    <a class="dropdown-item" href="{% url 'blog:user_logout' %}">Logout</a>

                  </div>
            </li>
            {% else %}
              <li class="nav-item">
                  <a href="{% url 'blog:user_login' %}" class="nav-link">Login</a>
              </li>
              {% endif %}
          </ul>
          <form action="{% url 'blog:post_list' %}" class="form-inline my-2 my-lg-0">
          
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='q'>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" >Search</button>
          </form>

        </div>
      </nav>